branch-defaults:
  master:
    environment: node-express-env
    group_suffix: null
global:
  application_name: eb-nginx-proxy-conf-2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
